# Generated by Django 5.2.12 on 2026-05-03 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=120)),
                ('parcel_id', models.CharField(blank=True, max_length=120)),
                ('governorate', models.CharField(db_index=True, max_length=150)),
                ('district', models.CharField(db_index=True, max_length=150)),
                ('village', models.CharField(db_index=True, max_length=150)),
                ('exploiter_name', models.CharField(blank=True, max_length=255)),
                ('basin_name', models.CharField(blank=True, max_length=255)),
                ('area', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='nile_lands.datasetversion')),
            ],
        ),
        migrations.CreateModel(
            name='UserGeoPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
